DROP USER gui CASCADE;
CREATE USER gui IDENTIFIED BY gui;
GRANT CONNECT, RESOURCE TO gui;

CONNECT gui/gui

DROP TABLE AUTOR CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_AUTOR;

DROP TABLE LIVRO CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_LIVRO;

CREATE SEQUENCE SEQ_AUTOR;
CREATE SEQUENCE SEQ_LIVRO;


CREATE TABLE AUTOR
(ID             NUMBER(5)
   CONSTRAINT AUTOR_ID_PK
   PRIMARY KEY,
 NOME          VARCHAR2(30)
   CONSTRAINT AUTOR_NOME_NN
   NOT NULL,
 DATA_NASCIMENTO   DATE
   CONSTRAINT AUTOR_DATA_NASCIMENTO_NN
   NOT NULL);
   
CREATE TABLE LIVRO
(ID             NUMBER(5)
   CONSTRAINT LIVRO_ID_PK
   PRIMARY KEY,
 NOME           VARCHAR2(30) 
   CONSTRAINT LIVRO_NOME_NN
   NOT NULL,
 SINOPSE      VARCHAR2(40),
 DATA_CADASTRO  DATE
   CONSTRAINT LIVRO_DATA_CADASTRO_NN
   NOT NULL,
 NUMERO_EXEMPLARES     NUMBER(5),
 AUTOR_ID     NUMBER(5)
   CONSTRAINT LIVRO_AUTOR_FK
   REFERENCES AUTOR(ID)
   CONSTRAINT LIVRO_AUTOR_ID_NN
   NOT NULL);


INSERT INTO AUTOR(ID, NOME, DATA_NASCIMENTO)
VALUES(SEQ_AUTOR.NEXTVAL, 'DAN BROWN', SYSDATE);
   
INSERT INTO AUTOR(ID, NOME, DATA_NASCIMENTO)
VALUES(SEQ_AUTOR.NEXTVAL, 'TOLKIEN', SYSDATE);



INSERT INTO LIVRO(ID, NOME, SINOPSE, DATA_CADASTRO, NUMERO_EXEMPLARES, AUTOR_ID)
VALUES(SEQ_LIVRO.NEXTVAL, 'ANJOS E DEMONIOS', 'BLA BLA BLA', SYSDATE, 50, 1);

INSERT INTO LIVRO(ID, NOME, SINOPSE, DATA_CADASTRO, NUMERO_EXEMPLARES, AUTOR_ID)
VALUES(SEQ_LIVRO.NEXTVAL, 'FORTALEZA DIGITAL', 'BLA BLA BLA BLA', SYSDATE, 50, 1);

INSERT INTO LIVRO(ID, NOME, SINOPSE, DATA_CADASTRO, NUMERO_EXEMPLARES, AUTOR_ID)
VALUES(SEQ_LIVRO.NEXTVAL, 'SENHOR DOS ANEIS', 'SDADNASKDNK', SYSDATE, 50, 2);

COMMIT;
